'use client';
import Link from 'next/link'; import {FormEvent,useEffect,useState} from 'react'; import {cartTotal,readCart,CartItem} from '../../lib/cart'; import {createOrder,getMe,validateCoupon,TOKEN_KEY} from '../../lib/auth'; import {useRouter} from 'next/navigation';
export default function CheckoutPage(){
 const router=useRouter(); const [items,setItems]=useState<CartItem[]>([]); const [token,setToken]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const [coupon,setCoupon]=useState(''); const [discount,setDiscount]=useState(0); const [couponMessage,setCouponMessage]=useState(''); const [paymentMethod,setPaymentMethod]=useState<'card'|'paypal'|'wallet'>('card');
 const [address,setAddress]=useState({name:'',line1:'',city:'',postcode:'',country:'United Kingdom'});
 useEffect(()=>{setItems(readCart());const t=localStorage.getItem(TOKEN_KEY)||'';setToken(t);if(!t)router.push('/login')},[router]);
 const subtotal=cartTotal(items); const shipping=subtotal>=100?0:items.length?7.99:0; const total=Math.max(0,subtotal+shipping-discount);
 async function applyCoupon(){setCouponMessage('');try{const result=await validateCoupon(coupon,subtotal);setDiscount(result.discount);setCouponMessage(`Coupon applied: -£${result.discount.toFixed(2)}`)}catch(e){setDiscount(0);setCouponMessage(e instanceof Error?e.message:'Invalid coupon')}}
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{if(!token)throw new Error('Please sign in first.');const me=await getMe(token);if(!me)throw new Error('Your session has expired. Please sign in again.');const order=await createOrder(token,{items:items.map(x=>({productId:x.productId,quantity:x.quantity})),shippingAddress:address,couponCode:coupon.trim()||undefined,paymentMethod});localStorage.removeItem('cp_cart');window.dispatchEvent(new Event('cp-cart-updated'));router.push('/order-success?order='+encodeURIComponent(order.orderNumber))}catch(err){setError(err instanceof Error?err.message:'Checkout failed')}finally{setBusy(false)}}
 return <main className="checkout-page"><Link href="/cart" className="back-link">Back to cart</Link><div className="checkout-grid">
 <form className="auth-card" onSubmit={submit}><span className="eyebrow">SECURE CHECKOUT</span><h1>Delivery details.</h1>{error&&<div className="form-error">{error}</div>}
 <label>Name<input required value={address.name} onChange={e=>setAddress({...address,name:e.target.value})}/></label><label>Address<input required value={address.line1} onChange={e=>setAddress({...address,line1:e.target.value})}/></label><label>City<input required value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/></label><label>Postcode<input required value={address.postcode} onChange={e=>setAddress({...address,postcode:e.target.value})}/></label><label>Country<input required value={address.country} onChange={e=>setAddress({...address,country:e.target.value})}/></label>
 <div className="checkout-section"><strong>Payment method</strong><div className="payment-options"><label><input type="radio" checked={paymentMethod==='card'} onChange={()=>setPaymentMethod('card')}/> Card</label><label><input type="radio" checked={paymentMethod==='paypal'} onChange={()=>setPaymentMethod('paypal')}/> PayPal</label><label><input type="radio" checked={paymentMethod==='wallet'} onChange={()=>setPaymentMethod('wallet')}/> Chacha Wallet</label></div></div>
 <button className="primary" disabled={busy||!items.length} type="submit">{busy?'Placing order…':'Place order · £'+total.toFixed(2)}</button></form>
 <aside className="summary"><span>ORDER SUMMARY</span><h2>£{total.toFixed(2)}</h2><p>Subtotal £{subtotal.toFixed(2)} · Shipping £{shipping.toFixed(2)} · Discount £{discount.toFixed(2)}</p><div className="coupon-box"><input placeholder="Coupon code" value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())}/><button type="button" onClick={applyCoupon} disabled={!coupon.trim()}>Apply</button></div>{couponMessage&&<small>{couponMessage}</small>}<hr/><span>PAYMENT SECURITY</span><p>Card details will be handled by the selected payment provider. Chacha Prime does not store raw card numbers.</p></aside>
 </div></main>
}